import { Metadata } from "next"

export const metadata:Metadata = {
  title:{
    default: 'My App',
    template: '%s | My App',
    
  },
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <header
        style={{
          backgroundColor: 'lightblue',
          padding: '1rem',
        }}
        >
          <p>Header</p>
        </header>
        {children}
        <footer
        style={{
          backgroundColor: 'lightgreen',
          padding: '1rem',
          // position: 'fixed',
          // bottom: 0,
          // width: '100%',
          // textAlign: 'center',
        }}
        >
          <p>Footer</p>
        </footer>
      </body>
    </html>
  )
}
